blueprint:
  name: SmartThings Button Control with Different Actions
  description: Handle SmartThings button presses with custom actions based on button type and press type.
  domain: automation
  input:
    button_device:
      name: Button Device
      description: The SmartThings button device
      default: []
      selector:
        text: {}
    # Button 1 Actions
    largeButton_pushed:
      name: Button 1 Pushed Action
      default: []
      selector:
        action: {}
    largeButton_held:
      name: Button 1 Held Action
      default: []
      selector:
        action: {}
    largeButton_pushed_2x:
      name: Button 1 Pushed 2x Action
      default: []
      selector:
        action: {}
    largeButton_pushed_3x:
      name: Button 1 Pushed 3x Action
      default: []
      selector:
        action: {}
    largeButton_pushed_4x:
      name: Button 1 Pushed 4x Action
      default: []
      selector:
        action: {}

    # Button 2 Actions
    button1_pushed:
      name: Button 2 Pushed Action
      default: []
      selector:
        action: {}
    button1_held:
      name: Button 2 Held Action
      default: []
      selector:
        action: {}
    button1_pushed_2x:
      name: Button 2 Pushed 2x Action
      default: []
      selector:
        action: {}
    button1_pushed_3x:
      name: Button 2 Pushed 3x Action
      default: []
      selector:
        action: {}
    button1_pushed_4x:
      name: Button 2 Pushed 4x Action
      default: []
      selector:
        action: {}

    # Button 3 Actions
    button2_pushed:
      name: Button 3 Pushed Action
      default: []
      selector:
        action: {}
    button2_held:
      name: Button 3 Held Action
      default: []
      selector:
        action: {}
    button2_pushed_2x:
      name: Button 3 Pushed 2x Action
      default: []
      selector:
        action: {}
    button2_pushed_3x:
      name: Button 3 Pushed 3x Action
      default: []
      selector:
        action: {}
    button2_pushed_4x:
      name: Button 3 Pushed 4x Action
      default: []
      selector:
        action: {}

    # Button 4 Actions
    button3_pushed:
      name: Button 4 Pushed Action
      default: []
      selector:
        action: {}
    button3_held:
      name: Button 4 Held Action
      default: []
      selector:
        action: {}
    button3_pushed_2x:
      name: Button 4 Pushed 2x Action
      default: []
      selector:
        action: {}
    button3_pushed_3x:
      name: Button 4 Pushed 3x Action
      default: []
      selector:
        action: {}
    button3_pushed_4x:
      name: Button 4 Pushed 4x Action
      default: []
      selector:
        action: {}

    # Button 5 Actions
    button4_pushed:
      name: Button 5 Pushed Action
      default: []
      selector:
        action: {}
    button4_held:
      name: Button 5 Held Action
      default: []
      selector:
        action: {}
    button4_pushed_2x:
      name: Button 5 Pushed 2x Action
      default: []
      selector:
        action: {}
    button4_pushed_3x:
      name: Button 5 Pushed 3x Action
      default: []
      selector:
        action: {}
    button4_pushed_4x:
      name: Button 5 Pushed 4x Action
      default: []
      selector:
        action: {}

mode: single
max_exceeded: silent

trigger:
  platform: event
  event_type: smartthings.button
  event_data:
    name: !input 'button_device'

action:
  - variables:
      component_id: "{{ trigger.event.data.component_id }}"
      value: "{{ trigger.event.data.value }}"
  - choose:
      # Button 1 Conditions
      - conditions: "{{ component_id == 'largeButton' }}"
        sequence:
          - choose:
              - conditions: "{{ value == 'pushed' }}"
                sequence: !input 'largeButton_pushed'
              - conditions: "{{ value == 'held' }}"
                sequence: !input 'largeButton_held'
              - conditions: "{{ value == 'pushed_2x' }}"
                sequence: !input 'largeButton_pushed_2x'
              - conditions: "{{ value == 'pushed_3x' }}"
                sequence: !input 'largeButton_pushed_3x'
              - conditions: "{{ value == 'pushed_4x' }}"
                sequence: !input 'largeButton_pushed_4x'

      # Button 2 Conditions
      - conditions: "{{ component_id == 'button1' }}"
        sequence:
          - choose:
              - conditions: "{{ value == 'pushed' }}"
                sequence: !input 'button1_pushed'
              - conditions: "{{ value == 'held' }}"
                sequence: !input 'button1_held'
              - conditions: "{{ value == 'pushed_2x' }}"
                sequence: !input 'button1_pushed_2x'
              - conditions: "{{ value == 'pushed_3x' }}"
                sequence: !input 'button1_pushed_3x'
              - conditions: "{{ value == 'pushed_4x' }}"
                sequence: !input 'button1_pushed_4x'

      # Button 3 Conditions
      - conditions: "{{ component_id == 'button2' }}"
        sequence:
          - choose:
              - conditions: "{{ value == 'pushed' }}"
                sequence: !input 'button2_pushed'
              - conditions: "{{ value == 'held' }}"
                sequence: !input 'button2_held'
              - conditions: "{{ value == 'pushed_2x' }}"
                sequence: !input 'button2_pushed_2x'
              - conditions: "{{ value == 'pushed_3x' }}"
                sequence: !input 'button2_pushed_3x'
              - conditions: "{{ value == 'pushed_4x' }}"
                sequence: !input 'button2_pushed_4x'

      # Button 4 Conditions
      - conditions: "{{ component_id == 'button3' }}"
        sequence:
          - choose:
              - conditions: "{{ value == 'pushed' }}"
                sequence: !input 'button3_pushed'
              - conditions: "{{ value == 'held' }}"
                sequence: !input 'button3_held'
              - conditions: "{{ value == 'pushed_2x' }}"
                sequence: !input 'button3_pushed_2x'
              - conditions: "{{ value == 'pushed_3x' }}"
                sequence: !input 'button3_pushed_3x'
              - conditions: "{{ value == 'pushed_4x' }}"
                sequence: !input 'button3_pushed_4x'

      # Button 5 Conditions
      - conditions: "{{ component_id == 'button4' }}"
        sequence:
          - choose:
              - conditions: "{{ value == 'pushed' }}"
                sequence: !input 'button4_pushed'
              - conditions: "{{ value == 'held' }}"
                sequence: !input 'button4_held'
              - conditions: "{{ value == 'pushed_2x' }}"
                sequence: !input 'button4_pushed_2x'
              - conditions: "{{ value == 'pushed_3x' }}"
                sequence: !input 'button4_pushed_3x'
              - conditions: "{{ value == 'pushed_4x' }}"
                sequence: !input 'button4_pushed_4x'

